# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_UI_1.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(643, 402)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.volumeSlider = QtWidgets.QSlider(self.tab)
        self.volumeSlider.setGeometry(QtCore.QRect(110, 100, 351, 22))
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setProperty("value", 50)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 511, 41))
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(40, 100, 47, 13))
        self.label_3.setObjectName("label_3")
        self.checkBox_username = QtWidgets.QCheckBox(self.tab)
        self.checkBox_username.setGeometry(QtCore.QRect(60, 210, 191, 17))
        self.checkBox_username.setObjectName("checkBox_username")
        self.voiceCombo = QtWidgets.QComboBox(self.tab)
        self.voiceCombo.setGeometry(QtCore.QRect(110, 170, 361, 22))
        self.voiceCombo.setObjectName("voiceCombo")
        self.rateSlider = QtWidgets.QSlider(self.tab)
        self.rateSlider.setGeometry(QtCore.QRect(110, 130, 361, 22))
        self.rateSlider.setMinimum(-100)
        self.rateSlider.setMaximum(100)
        self.rateSlider.setProperty("value", 25)
        self.rateSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rateSlider.setObjectName("rateSlider")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(40, 130, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 300, 591, 21))
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(40, 170, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(10, 270, 601, 16))
        self.label_6.setObjectName("label_6")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(20, 610, 47, 13))
        self.label_14.setObjectName("label_14")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(40, 60, 301, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(400, 60, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 0, 401, 61))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(10, 272, 499, 45))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(20, 171, 499, 45))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(20, 222, 499, 44))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(10, 19, 601, 45))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(20, 120, 499, 45))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(10, 70, 541, 44))
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">The program need Google Chrome to run, so please don\'t close is.</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Volume"))
        self.checkBox_username.setText(_translate("MainWindow", "You will not pronounce the n-word"))
        self.label_2.setText(_translate("MainWindow", "Speed"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">If Google Chrome is open, please don\'t touch the app, due to a coding problem.</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Voice"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Make sure that GOOGLE CHROME is closed if you wanna change the volume of the sound or voice speed.</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "...."))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Just enter the twitch channel name:</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Enter the name of your twitch channel:</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Home"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">The program still in development</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Twitter: </span><a href=\"https://twitter.com/NBelaatik\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;\">https://twitter.com/NBelaatik</span></a></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Discord: </span><a href=\"https://discord.gg/mgXheAe\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;\">https://discord.gg/mgXheAe</span></a></p></body></html>"))
        self.label_11.setToolTip(_translate("MainWindow", "<html><head/><body><p><a href=\"https://www.facebook.com/Night.C0de\"><span style=\" text-decoration: underline; color:#0000ff;\">If you have any problem just contact me at:</span></a></p></body></html>"))
        self.label_11.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">If you have any problem just contact me at:</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">This application create by Night_Code, and this is the version 1.2</span></p></body></html>"))
        self.label_12.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'JetBrains Mono\'; font-size:18pt; font-weight:600; color:#000000;\"> Facebook: </span><a href=\"https://www.facebook.com/Night.C0de\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.facebook.com/Night.C0de</span></a></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Facebook: </span><a href=\"https://www.facebook.com/Night.C0de\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline; color:#0000ff;\">https://www.facebook.com/Night.C0de</span></a></p></body></html>"))
        self.label_13.setToolTip(_translate("MainWindow", "<html><head/><body><p><a href=\"https://www.facebook.com/Night.C0de\"><span style=\" text-decoration: underline; color:#0000ff;\">If you have any problem just contact me at:</span></a></p></body></html>"))
        self.label_13.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">If you have any problem just contact me at:</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">If you have any problem or suggestion please contact me at:</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Help"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
